/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.managerController;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author azhar
 */
public class tambahRuangan extends javax.swing.JFrame implements ChangeListener, addListener{

    /**
     * Creates new form tambahRuangan
     */
    public tambahRuangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tf_namaRuangan = new javax.swing.JTextField();
        Ta_lokasi = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        Sl_rating = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        tf_luasRuangan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Btn_back = new javax.swing.JButton();
        cb_ac = new javax.swing.JCheckBox();
        cb_TV = new javax.swing.JCheckBox();
        cb_mejaRapat = new javax.swing.JCheckBox();
        cb_projector = new javax.swing.JCheckBox();
        cb_papanTulis = new javax.swing.JCheckBox();
        cb_wifi = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        BtnDaftar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Tf_harga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama             :");

        jLabel2.setText("Lokasi            :");

        Ta_lokasi.setColumns(20);
        Ta_lokasi.setLineWrap(true);
        Ta_lokasi.setRows(5);

        jLabel3.setText("Rating             :");

        Sl_rating.setMajorTickSpacing(10);
        Sl_rating.setMaximum(50);
        Sl_rating.setMinorTickSpacing(5);
        Sl_rating.setPaintTicks(true);
        Sl_rating.setSnapToTicks(true);
        Sl_rating.setToolTipText("");
        Sl_rating.setValue(0);
        Sl_rating.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Sl_rating.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sl_ratingStateChanged(evt);
            }
        });

        jLabel4.setText("Luas Ruangan :");

        tf_luasRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_luasRuanganActionPerformed(evt);
            }
        });

        jLabel5.setText("Fasilitas          :");

        jLabel6.setText("m2");

        Btn_back.setText("Back");
        Btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_backActionPerformed(evt);
            }
        });

        cb_ac.setText("AC");

        cb_TV.setText("TV");
        cb_TV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TVActionPerformed(evt);
            }
        });

        cb_mejaRapat.setText("Meja Rapat");
        cb_mejaRapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mejaRapatActionPerformed(evt);
            }
        });

        cb_projector.setText("Projector");

        cb_papanTulis.setText("Papan Tulis");

        cb_wifi.setText("Wifi");

        jLabel7.setText(""+Sl_rating.getValue());

        BtnDaftar.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        BtnDaftar.setText("Daftar");
        BtnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDaftarActionPerformed(evt);
            }
        });

        jLabel8.setText("Harga              :");

        jLabel9.setText("/jam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Btn_back)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnDaftar)
                        .addGap(194, 194, 194))))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(Tf_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_luasRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Sl_rating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb_mejaRapat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_wifi))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_projector)
                                    .addComponent(cb_ac))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_TV)
                                    .addComponent(cb_papanTulis)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Ta_lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(Tf_namaRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Btn_back)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Tf_namaRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Ta_lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sl_rating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_luasRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_TV)
                            .addComponent(cb_ac))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb_papanTulis)
                            .addComponent(cb_projector, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_mejaRapat)
                    .addComponent(cb_wifi))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Tf_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(22, 22, 22)
                .addComponent(BtnDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_luasRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_luasRuanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_luasRuanganActionPerformed

    private void cb_TVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_TVActionPerformed

    private void cb_mejaRapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mejaRapatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_mejaRapatActionPerformed

    private void Sl_ratingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sl_ratingStateChanged
        Sl_rating.addChangeListener(this);
    }//GEN-LAST:event_Sl_ratingStateChanged

    private void Btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_backActionPerformed

    }//GEN-LAST:event_Btn_backActionPerformed

    private void BtnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahRuangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDaftar;
    private javax.swing.JButton Btn_back;
    private javax.swing.JSlider Sl_rating;
    private javax.swing.JTextArea Ta_lokasi;
    private javax.swing.JTextField Tf_harga;
    private javax.swing.JTextField Tf_namaRuangan;
    private javax.swing.JCheckBox cb_TV;
    private javax.swing.JCheckBox cb_ac;
    private javax.swing.JCheckBox cb_mejaRapat;
    private javax.swing.JCheckBox cb_papanTulis;
    private javax.swing.JCheckBox cb_projector;
    private javax.swing.JCheckBox cb_wifi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tf_luasRuangan;
    // End of variables declaration//GEN-END:variables

    @Override
    public void stateChanged(ChangeEvent e) {
        jLabel7.setText(""+Sl_rating.getValue());
    }

    public JButton getBtn_back() {
        return Btn_back;
    }

    public JSlider getSl_rating() {
        return Sl_rating;
    }

    public JTextArea getTa_lokasi() {
        return Ta_lokasi;
    }

    public JTextField getTf_namaRuangan() {
        return Tf_namaRuangan;
    }

    public JCheckBox getCb_TV() {
        return cb_TV;
    }

    public JCheckBox getCb_ac() {
        return cb_ac;
    }

    public JCheckBox getCb_mejaRapat() {
        return cb_mejaRapat;
    }

    public JCheckBox getCb_papanTulis() {
        return cb_papanTulis;
    }

    public JCheckBox getCb_projector() {
        return cb_projector;
    }

    public JCheckBox getCb_wifi() {
        return cb_wifi;
    }

    public JTextField getTf_luasRuangan() {
        return tf_luasRuangan;
    }

    public JButton getBtnDaftar() {
        return BtnDaftar;
    }

    public JTextField getTf_harga() {
        return Tf_harga;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    @Override
    public void addActionListener(ActionListener e) {
        Btn_back.addActionListener(e);
        BtnDaftar.addActionListener(e);
    }
}
